
function StateSuggestions1() {
//alert ("Meow..");
this.states = 
[
"LT401 || BLOOD GLUCOSE [ RANDOM ] - BIOCHEMISTRY","LT402 || SERUM URIC ACID - BIOCHEMISTRY","LT404 || S. BILIRUBIN TOTAL - BIOCHEMISTRY","LT405 || S. BILIRUBIN DIRECT - BIOCHEMISTRY","LT406 || S. BILIRUBIN INDIRECT - BIOCHEMISTRY","LT424 || S. S G O T - BIOCHEMISTRY","LT425 || S. S G P T - BIOCHEMISTRY","LT426 || S. GAMA GT - BIOCHEMISTRY","LT427 || S. ALKALINE PHOSPHATE - BIOCHEMISTRY","LT428 || S. TOTAL PROTEIN - BIOCHEMISTRY","LT429 || S. ALBUMIN - BIOCHEMISTRY","LT430 || S. GLOBULIN - BIOCHEMISTRY","LT431 || A/G   RATIO - BIOCHEMISTRY","LT448 || BLOOD SUGAR [ R ] - BIOCHEMISTRY","LT415 || BLOOD GLUCOSE [ FASTING ] - BIOCHEMISTRY - BLOOD EXAMINATION","LT416 || BLOOD GLUCOSE [ P.P. ] - BIOCHEMISTRY - BLOOD EXAMINATION","LT432 || MP & MF [ BY  QBC ] - BLOOD PARASITES","LT407 || SPECIMEN - CLINICAL  PATHOLOGY - URINE  EXAMINATION","LT408 || COLOUR - CLINICAL  PATHOLOGY - URINE  EXAMINATION","LT409 || TRANSPERANCY - CLINICAL  PATHOLOGY - URINE  EXAMINATION","LT410 || PROTEIN - CLINICAL  PATHOLOGY - URINE  EXAMINATION","LT411 || SUGAR  [ R ] - CLINICAL  PATHOLOGY - URINE  EXAMINATION","LT412 || DEPOSIT - CLINICAL  PATHOLOGY - URINE  EXAMINATION","LT413 || BILE  SALT - CLINICAL  PATHOLOGY - URINE  EXAMINATION","LT414 || BILE  PIGMENT - CLINICAL  PATHOLOGY - URINE  EXAMINATION","LT452 || URINE  PREGNANCY  TEST - BY  PREG – CARD - CLINICAL  PATHOLOGY - URINE  EXAMINATION","LT442 || TRIIODOTHYRONINE [ FREE   T3 ] - ENDOCRINOLOGY - BLOOD EXAMINATION","LT443 || THYROXINE [ FREE T4 ] - ENDOCRINOLOGY - BLOOD EXAMINATION","LT444 || THYROID STIMULATING HORMONE [ TSH ] - ENDOCRINOLOGY - BLOOD EXAMINATION","LT445 || HB A 1 C - ENDOCRINOLOGY - BLOOD EXAMINATION","LT446 || BLOOD GROUPING & RH [ D ]  TYPING - HAEMATOLOGY - BLOOD EXAMINATION","LT447 || BLOOD HAEMOGLOBIN [HB] - HAEMATOLOGY - BLOOD EXAMINATION","LT457 || A. S. O. TITRE - IMMUNOLOGY - RHEUMATOID  FACTOR","LT458 || R . A . FACTOR - IMMUNOLOGY - RHEUMATOID  FACTOR","LT459 || C REACTIVE   PROTEIN - IMMUNOLOGY - RHEUMATOID  FACTOR","LT403 || LEPTOSPIROSIS MAT – G - LEPTO ASSAY","LT419 || TOTAL CHOLESTEROL - LIPID PROFILE - FASTING","LT420 || HDL CHOLESTEROL - LIPID PROFILE - FASTING","LT421 || LDL CHOLESTEROL - LIPID PROFILE - FASTING","LT422 || VLDL CHOLESTEROL - LIPID PROFILE - FASTING","LT423 || SERUM TRIGLYCERIDES - LIPID PROFILE - FASTING","LT462 || S. BILIRUBIN TOTAL - LIVER FUNCTION TEST","LT463 || S. BILIRUBIN  DIRECT - LIVER FUNCTION TEST","LT464 || S. BILIRUBIN  INDIRECT - LIVER FUNCTION TEST","LT465 || S . S G O T - LIVER FUNCTION TEST","LT466 || S . S G P T - LIVER FUNCTION TEST","LT467 || S . GAMA GT - LIVER FUNCTION TEST","LT468 || S . ALKALINE PHOSPHATE - LIVER FUNCTION TEST","LT469 || S . TOTAL PROTEIN - LIVER FUNCTION TEST","LT470 || S . ALBUMIN - LIVER FUNCTION TEST","LT471 || S. GLOBULIN - LIVER FUNCTION TEST","LT472 || A / G  RATIO - LIVER FUNCTION TEST","LT400 || S. PARA TYPHI ‘BH’ ANTIGEN - MICROBIOLOGY","LT460 || ANTI TB IGG - MICROBIOLOGY - BLOOD EXAMINATION","LT461 || ANTI TB IGM - MICROBIOLOGY - BLOOD EXAMINATION","LT433 || SPECIMEN - MICROBIOLOGY - URINE CULTURE - SENSITIVITY","LT434 || TYPE OF CULTURE - MICROBIOLOGY - URINE CULTURE - SENSITIVITY","LT435 || ORGANISM GROWN - MICROBIOLOGY - URINE CULTURE - SENSITIVITY","LT436 || COLONY COUNT - MICROBIOLOGY - URINE CULTURE - SENSITIVITY","LT437 || SENSITIVE  TO - MICROBIOLOGY - URINE CULTURE - SENSITIVITY","LT438 || MODERTELY SENSITIVE TO - MICROBIOLOGY - URINE CULTURE - SENSITIVITY","LT439 || TRIIODOTHYRONINE [ T3 ] - MICROBIOLOGY - URINE CULTURE - SENSITIVITY","LT440 || THYROXINE [ T4 ] - MICROBIOLOGY - URINE CULTURE - SENSITIVITY","LT441 || THYROID STIMULATING HORMONE [ TSH ] - MICROBIOLOGY - URINE CULTURE - SENSITIVITY","LT449 || V . D . R . L - SEROLOGY","LT450 || HBSAG - SEROLOGY","LT451 || HIV  I & II - SEROLOGY","LT491 || HCV - SEROLOGY","LT473 || HIV 1 GP 160 ( ENV ) - SEROLOGY - WESTERN BLOT TEST - HIV I & II","LT474 || HIV 1 GP 120 ( ENV ) - SEROLOGY - WESTERN BLOT TEST - HIV I & II","LT475 || HIV 1 P66  ( POL ) - SEROLOGY - WESTERN BLOT TEST - HIV I & II","LT476 || HIV 1 P51 ( POL ) - SEROLOGY - WESTERN BLOT TEST - HIV I & II","LT477 || HIV 1 P55 ( GAG ) - SEROLOGY - WESTERN BLOT TEST - HIV I & II","LT478 || HIV 1 P41 ( ENV ) - SEROLOGY - WESTERN BLOT TEST - HIV I & II","LT479 || HIV 1 P31 ( POL ) - SEROLOGY - WESTERN BLOT TEST - HIV I & II","LT480 || HIV 1 P24 ( GAG ) - SEROLOGY - WESTERN BLOT TEST - HIV I & II","LT481 || HIV 1 P17 ( GAG ) - SEROLOGY - WESTERN BLOT TEST - HIV I & II","LT482 || HIV  -- II - SEROLOGY - WESTERN BLOT TEST - HIV I & II","LT453 || RBCS - SMEAR  STUDY","LT454 || WBCS - SMEAR  STUDY","LT455 || PLATELT - SMEAR  STUDY","LT456 || PARASITE - SMEAR  STUDY","LT417 || URINE  SUGAR  [ FASTING ] - URINE EXAMINATION","LT418 || URINE SUGAR  [ P.P. ] - URINE EXAMINATION"];
}

/**
 * Request suggestions for the given autosuggest control. 
 * @scope protected
 * @param oAutoSuggestControl The autosuggest control to provide suggestions for.
 */
StateSuggestions1.prototype.requestSuggestions = function (oAutoSuggestControl /*:AutoSuggestControl*/,
                                                          bTypeAhead /*:boolean*/) {
    var aSuggestions = [];
    var sTextboxValue = oAutoSuggestControl.textbox.value;
    //alert (sTextboxValue);
	//Dummy value to have one intentional blank space to allow down and up keys to select items is list contains only one item.
	var varDummyValue = " "; 
	
 	var loopLength = 0;

    if (sTextboxValue.length > 0){
	
	var sTextboxValue = sTextboxValue.toUpperCase();

        //search for matching states
        for (var i=0; i < this.states.length; i++) 
		{ 
            if (this.states[i].indexOf(sTextboxValue) >= 0) 
			{
                loopLength = loopLength + 1;
				if (loopLength <= 15) //TO REDUCE THE SUGGESTIONS DROP DOWN LIST
				{
					aSuggestions.push(this.states[i]);
				}
            } 
        }
    }

	aSuggestions.push(varDummyValue);
    //provide suggestions to the control
    oAutoSuggestControl.autosuggest(aSuggestions, bTypeAhead);
};